### ISSUE TITLE
MAPA MENTAL

### ISSUE THREAD

**Issue by carla1131** [SistemasTecTlaxiaco/actividad-4-mapa-mental-carla1131#2]
![MAPA CONCEPTUAL_BAUTISTA LEON CARLA;1AS](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-carla1131/assets/144480662/515fc271-519d-4683-bab2-64c61d81636a)

**Comment by LuisAlexisMorales** [comment]
Manejo conceptual:25%
Relación entre concepto:25%
Calidad de la presentación:25%
Jerarquía:22%
Total:97%.      CalFinal:19.4
Calificado por el equipo de: Luis Alexis Morales

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
